# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.ceramicshears
mod_version=3.6.0.1
mod_id=ceramicshears
mod_name=Ceramic Shears
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/CeramicShears
mod_issue_tracker=https://github.com/cech12/CeramicShears/issues
description=A mod which adds Ceramic Shears.

# Common
java_version=21
minecraft_version=1.21.9
minecraft_version_range=[1.21.9, 1.22)

# Fabric
fabric_version=0.134.0+1.21.9
fabric_loader_version=0.17.3
cloth_config_version=20.0.148
mod_menu_version=16.0.0-rc.1

# Forge
forge_version=59.0.5
forge_version_range=[59.0.5,)
forge_loader_version_range=[59,)

# NeoForge
neoforge_version=21.9.15-beta
neoforge_version_range=[21.9.15-beta,)
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false